apiVersion: v1
kind: List
items:
  - apiVersion: argoproj.io/v1alpha1
    kind: AppProject
    metadata:
      name: argocd
      namespace: argocd
    spec:
      description: Argocd Project
      sourceRepos:
        - '*'
      destinations:
        - namespace: argocd
          server: https://kubernetes.default.svc
      clusterResourceWhitelist:
        - group: '*'
          kind: '*'
      orphanedResources:
        warn: false
